# Generated by Django 5.1 on 2024-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
